# Options for the Basalt SLAM Tracker

# Show GUI
show-gui=0

# Ground-truth camera calibration used for simulation.
cam-calib="D:\\Uni\\Master_Thesis\\monado\\d435i_calib.json"

# Path to config file.
config-path="D:\\Uni\\Master_Thesis\\monado\\default_config.json"

# Path to folder where marginalization data will be stored.
marg-data=""

# Poll and print for queue sizes.
print-queue=0

# Whether to use a double or single precision pipeline.
use-double=0

# Whether to use a pipeline that produces repeatable outputs
deterministic=0
